
GO:=go
GOFMT:=gofmt
BMPINSPECT_EXE:=bmpinspect

all: $(BMPINSPECT_EXE)
.PHONY: all clean

$(BMPINSPECT_EXE): bmpinspect.go
	$(GO) build -o $@ bmpinspect.go

%.go.fmt: %.go
	$(GOFMT) $< > $@

clean:
	rm -f $(BMPINSPECT_EXE)

